# Install Postgres 15 using Ansible
- name: Install PostgreSQL
  hosts: db
  become: true

  tasks:
    - name: Install python and pyscopg2
      apt:
        name:
          - python3
          - python3-pip
          - python3-psycopg2
        state: present

    - name: Add PostgreSQL GPG key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install PostgreSQL 15
      apt:
        name: postgresql-15
        state: present

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Create user appuser
      become: true
      postgresql_user:
        name: appuser
        password: "{{ 'appuser_password' | password_hash('sha512') }}"
        role_attr_flags: LOGIN
        state: present

    - name: Create database mydb
      become: true
      postgresql_db:
        name: mydb
        state: present

    - name: Grant privileges to appuser on mydb
      become: true
      postgresql_privs:
        db: mydb
        role: appuser
        privs: ALL
